[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/theomjones/netlify-test"